### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/uio-carpentry.github.io#49]
At https://uio-carpentry.github.io/workshops/, (at least) these workshops have broken links:

* May Carpentry@UiO Data Analysis and Visualization in R and Tidyverse (Novices) - goes to https://www.ub.uio.no/english/courses-events/courses/other/Carpentry/time-and-place/210525_r which is broken
* March Carpentry: Plotting and Programming with Python (Novices) - similar issue
* January Carpentry pilot Workshop (Online): Introduction to Conda for (Data) Scientists - similar issue

It lokks like other links to ub.uio.no pages are also broken.

(by the way, does the Hugo step we use have a link checker?)

**Comment by arockenberger** [comment]
The problem might be the following: USIT deletes old (course) pages. Often without any notification. It's something we have taken up with our local nettredaktør without much success.

**Comment by arockenberger** [comment]
Fixed the broken links for 2021 courses (https://github.com/uio-carpentry/uio-carpentry.github.io/commit/99c79dac2108a951300a06384010cfe1409ade10)

**Comment by arockenberger** [comment]
Problem seems to be that web admin changed location of the courses internally; so they are still there, but not where they were before. Dislike.

**Comment by arockenberger** [comment]
This is too much to do without a concerted effort; anyone volunteering? @ainor-star @annesbe

**Comment by arockenberger** [comment]
Problem is multi-layered. Some links go to websites at UB, some links only refer to the websites we make on GitHub. There's no consistency, I think mainly due to the fact that the UB websites seem to be more ephemeral than the GitHub ones.

Loke (from DSC) is working on a solution for updating the broken links.

However, we (the Board) should decide which webpage we want to refer to and how to keep a record (i.e. archiving websites!
@lexnederbragt @Teebusch @annesbe @vivigirardin @ainor-star @arockenberger

**Comment by arockenberger** [comment]
All fixed thanks to Loke! Closing Issue (https://github.com/uio-carpentry/uio-carpentry.github.io/commit/e1bfd990b559183d902cfc6fa79efe82da06f425)
